### PR TITLE
Prepend language token and task id when using multilingual model

### PR DESCRIPTION
**Pull request by pxl-th**
When using multilingual model we have to prepend `<language id>` + `<task id>` before passing tokens to transcribtion.

- Update deps.
- Update README.

### CODE REVIEW

**Comment by pxl-th** [comment]
@Benoit9 if you can merge this PR into your branch we can then proceed with merging multilingual support to main.

**Comment by Benoit9** [comment]
done, but I don't think it's correct. The multilingual models work for english, so it should not insist on a .en model.

Also, my understanding is that the language and task tokens are optional. If you don't specify them, you get automatic selection.

**Comment by Benoit9** [comment]
LOL, when I select "french" and a feed a french recording of mine to large-v3, it translates to english. It did not do that without the language and task tokens. And with tiny, base, small or medium, it does not either (correctly transcribes french).

**Comment by pxl-th** [comment]
> The multilingual models work for english, so it should not insist on a .en model.

Yes, we can probably relax that.

> Also, my understanding is that the language and task tokens are optional. If you don't specify them, you get automatic selection.

Without specifying task token and the language I was getting one part of the audio transcribed to the original language while the other was translated to the english and so on.

**Comment by pxl-th** [comment]
> LOL, when I select "french" and a feed a french recording of mine to large-v3, it translates to english. It did not do that without the language and task tokens.

Can you inspect if it adds task and language tokens [here](LOL, when I select "french" and a feed a french recording of mine to large-v3, it translates to english. It did not do that without the language and task tokens.)?

**Comment by pxl-th** [comment]
You can also comment that out to see if transcribes correctly

**Comment by Benoit9** [comment]
> > The multilingual models work for english, so it should not insist on a .en model.
> 
> Yes, we can probably relax that.
> 

The largest models are _only_ multilingual, they are the only large options for English.

This is incorrect in tokenizer.jl:164
`    multilingual = language != "english"
`

**Comment by Benoit9** [comment]
> You can also comment that out to see if transcribes correctly

Yes it does,

**Comment by pxl-th** [comment]
I see, so we should probably make task & language tokens optional.

**Comment by Benoit9** [comment]
Yes, I think that's what the Huggingface implementation does.

**Pull request merged**
